# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftDogApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 4.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'

  # Pods for RxSwiftDogApp


  # Might need specific pods for testing RxSwift
  target 'RxSwiftDogAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxSwiftDogAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
