# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DogAppSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher', '~> 4.0'

  # Pods for DogAppSwift

  target 'DogAppSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DogAppSwiftUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
